/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TacImport } from './routes/tac'
import { Route as ResultsImport } from './routes/results'
import { Route as LoadingImport } from './routes/loading'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TacRoute = TacImport.update({
  id: '/tac',
  path: '/tac',
  getParentRoute: () => rootRoute,
} as any)

const ResultsRoute = ResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRoute,
} as any)

const LoadingRoute = LoadingImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingImport
      parentRoute: typeof rootRoute
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsImport
      parentRoute: typeof rootRoute
    }
    '/tac': {
      id: '/tac'
      path: '/tac'
      fullPath: '/tac'
      preLoaderRoute: typeof TacImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/results': typeof ResultsRoute
  '/tac': typeof TacRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/results': typeof ResultsRoute
  '/tac': typeof TacRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/results': typeof ResultsRoute
  '/tac': typeof TacRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loading' | '/results' | '/tac'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loading' | '/results' | '/tac'
  id: '__root__' | '/' | '/loading' | '/results' | '/tac'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadingRoute: typeof LoadingRoute
  ResultsRoute: typeof ResultsRoute
  TacRoute: typeof TacRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadingRoute: LoadingRoute,
  ResultsRoute: ResultsRoute,
  TacRoute: TacRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/loading",
        "/results",
        "/tac"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/loading": {
      "filePath": "loading.tsx"
    },
    "/results": {
      "filePath": "results.tsx"
    },
    "/tac": {
      "filePath": "tac.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
